<?php
namespace Beech\Ehrm\Aspect;

/*
 * This source file is proprietary property of Beech Applications B.V.
 * Date: 24-07-12 16:19
 * All code (c) Beech Applications B.V. all rights reserved
 */

use TYPO3\Flow\Annotations as Flow;

/**
 * Aspect allows for fetching an alternative yaml settings file for a form generated by the formbuilder
 * TYPO3.Formbuilder forms are stored in a .yaml file in /Data/Forms/
 * Copy a (modified) generated file to the /Beech.Ehrm/Resources/Private/Wizards folder to alter default behaviour
 *
 * @Flow\Aspect
 */
class FormBuilderYamlPersistenceAspect {

	/**
	 * @var string
	 */
	protected $alternativeSavePath = 'resource://Beech.Ehrm/Private/Wizards/';

	/**
	 * Load alternative wizard file if one is found
	 *
	 * @param  \TYPO3\Flow\Aop\JoinPointInterface $joinPoint
	 * @Flow\Around("method(TYPO3\Form\Persistence\YamlPersistenceManager->getFormPathAndFilename())")
	 * @return string the absolute path and filename of the form with the specified $persistenceIdentifier
	 */
	public function getAlternativeFormPathAndFilename(\TYPO3\Flow\Aop\JoinPointInterface $joinPoint) {
		$persistenceIdentifier = $joinPoint->getMethodArgument('persistenceIdentifier');
		$alternativeFile = \TYPO3\Flow\Utility\Files::concatenatePaths(array($this->alternativeSavePath, sprintf('%s.yaml', $persistenceIdentifier)));
		if (file_exists($alternativeFile)) {
			return $alternativeFile;
		}

		$result = $joinPoint->getAdviceChain()->proceed($joinPoint);
		return $result;
	}
}

?>