Radmiraal:
  Emberjs:
    restInterfaces:
      task:
        routePath: 'tasks'
        model: 'Beech\Task\Domain\Model\Task'
        repository: 'Beech\Task\Domain\Repository\TaskRepository'
      priority:
        routePath: 'priorities'
        model: 'Beech\Task\Domain\Model\Priority'
        repository: 'Beech\Task\Domain\Repository\PriorityRepository'