Radmiraal:
  Emberjs:
    restInterfaces:
      beech_task_domain_model_task:
        routePath: 'beech_task_domain_model_tasks'
        model: 'Beech\Task\Domain\Model\Task'
        repository: 'Beech\Task\Domain\Repository\TaskRepository'
