<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120904154119 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$this->addSql("ALTER TABLE beech_party_domain_model_address CHANGE type type VARCHAR(30) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE postalcode postalcode VARCHAR(255) DEFAULT NULL, CHANGE residence residence INT DEFAULT NULL, CHANGE street street VARCHAR(255) DEFAULT NULL, CHANGE housenumber housenumber INT DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE postbox postbox INT DEFAULT NULL");
		$this->addSql("ALTER TABLE beech_party_domain_model_company CHANGE companynumber companynumber VARCHAR(255) DEFAULT NULL, CHANGE companytype companytype VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE legalform legalform VARCHAR(255) DEFAULT NULL, CHANGE chamberofcommercenumber chamberofcommercenumber VARCHAR(255) DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$this->addSql("ALTER TABLE beech_party_domain_model_address CHANGE type type VARCHAR(30) DEFAULT NULL, CHANGE code code VARCHAR(255) NOT NULL, CHANGE postalcode postalcode VARCHAR(255) NOT NULL, CHANGE postbox postbox INT NOT NULL, CHANGE residence residence INT NOT NULL, CHANGE street street VARCHAR(255) NOT NULL, CHANGE housenumber housenumber INT NOT NULL, CHANGE description description VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE beech_party_domain_model_company CHANGE companynumber companynumber VARCHAR(255) NOT NULL, CHANGE companytype companytype VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL, CHANGE chamberofcommercenumber chamberofcommercenumber VARCHAR(255) NOT NULL, CHANGE legalform legalform VARCHAR(255) NOT NULL");
	}
}

?>