<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120905115938 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE beech_party_domain_model_company CHANGE chamberofcommercenumber chamberofcommercenumber VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE beech_party_domain_model_address CHANGE postbox postbox VARCHAR(255) DEFAULT NULL, CHANGE residence residence VARCHAR(255) DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE beech_party_domain_model_address CHANGE postbox postbox INT DEFAULT NULL, CHANGE residence residence INT DEFAULT NULL");
		$this->addSql("ALTER TABLE beech_party_domain_model_company CHANGE chamberofcommercenumber chamberofcommercenumber VARCHAR(255) DEFAULT NULL");
	}
}

?>