-
  name: 'Company management'
  uriPattern: 'management/company(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Company'
    '@action': 'list'
    '@format': 'html'

-
  name: 'ToDo list'
  uriPattern: 'management/todo(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\ToDo'
    '@action': 'index'
    '@format': 'html'
