-
  name: 'Company management'
  uriPattern: 'management/company(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Company'
    '@action': 'list'
    '@format': 'html'
  appendExceedingArguments: true
-
  name: 'Person management with format'
  uriPattern: 'management/person/{@action}(.{@format})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Person'
    '@action': 'list'

-
  name: 'Person management'
  uriPattern: 'management/person(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Person'
    '@action': 'list'
    '@format': 'html'

-
  name: 'GroupType management'
  uriPattern: 'management/grouptype(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Group\Type'
    '@action': 'list'
    '@format': 'html'

-
  name: 'Accounts management'
  uriPattern: 'management/account(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Account'
    '@action': 'list'
    '@format': 'html'

-
  name: 'Group management'
  uriPattern: 'management/group(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Group'
    '@action': 'list'
    '@format': 'html'
