-
  name: 'Notification REST service'
  uriPattern: 'rest/notification'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Rest\Notification'
    '@action': 'list'
    '@format': 'json'

-
  name: 'Notification REST service'
  uriPattern: 'rest/notification(/{resource})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Rest\Notification'
    '@action': 'delete'
    '@format': 'json'

-
  name: 'Company management'
  uriPattern: 'management/company(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Company'
    '@action': 'list'
    '@format': 'html'
  appendExceedingArguments: true
-
  name: 'Person management with format'
  uriPattern: 'management/person/{@action}(.{@format})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Person'
    '@action': 'list'

-
  name: 'Person management'
  uriPattern: 'management/person(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\Person'
    '@action': 'list'
    '@format': 'html'

-
  name: 'ToDo list'
  uriPattern: 'management/todo(/{@action})'
  defaults:
    '@package': 'Beech.Party'
    '@controller': 'Management\ToDo'
    '@action': 'index'
    '@format': 'html'
