Radmiraal:
  Emberjs:
    restInterfaces:
      beech_party_domain_model_person:
        routePath: 'beech_party_domain_model_persons'
        model: 'Beech\Party\Domain\Model\Person'
        repository: 'Beech\Party\Domain\Repository\PersonRepository'
      beech_party_domain_model_company:
        routePath: 'beech_party_domain_model_companies'
        model: 'Beech\Party\Domain\Model\Company'
        repository: 'Beech\Party\Domain\Repository\CompanyRepository'
