Beech:
  Ehrm:
    modules:
      admin:
        menu:
          companyNew:
            label: 'Company'
            priority: 20
            menuGroup: 'main:new'
            package: 'Beech.Party'
            controller: 'Management\Company'
            resource: 'ManagementControllers'
            action: 'new'
          companyList:
            label: 'Companies'
            priority: 20
            menuGroup: 'main:manage'
            package: 'Beech.Party'
            controller: 'Management\Company'
            resource: 'ManagementControllers'
            action: 'list'
          personList:
            label: 'People'
            priority: 30
            menuGroup: 'main:manage'
            package: 'Beech.Party'
            controller: 'Management\Person'
            resource: 'ManagementControllers'
            action: 'list'

    menu:
      account:
        menu:
          todo:
            label: 'Todo'
            priority: 30
            package: 'Beech.Party'
            controller: 'management\todo'
            action: 'index'

          settings:
            label: 'Settings'
            priority: 20
            controller: 'Setup'
            action: 'index'
