Beech:
  Ehrm:
    modules:
      admin:
        menu:
          companyNew:
            label: 'Company'
            priority: 20
            menuGroup: 'main:new'
            package: 'Beech.Party'
            controller: 'Management\Company'
            resource: 'ManagementControllers'
            action: 'new'
          companyList:
            label: 'Companies'
            priority: 20
            menuGroup: 'main:manage'
            package: 'Beech.Party'
            controller: 'Management\Company'
            resource: 'ManagementControllers'
            action: 'list'
          personList:
            label: 'People'
            priority: 30
            menuGroup: 'main:manage'
            package: 'Beech.Party'
            controller: 'Management\Person'
            resource: 'ManagementControllers'
            action: 'list'
          groupTypeList:
            label: 'Group Types'
            priority: 40
            menuGroup: 'main:manage'
            package: 'Beech.Party'
            controller: 'Management\Group\Type'
            resource: 'ManagementControllers'
            action: 'list'

    menu:
      administration:
        groups:
          persons:
            priority: 10
            label: 'Persons'
          companies:
            priority: 20
            label: 'Companies'
      account:
        menu:
          todo:
            label: 'Todo'
            priority: 30
            package: 'Beech.Party'
            controller: 'management\todo'
            action: 'index'

          settings:
            label: 'Settings'
            priority: 20
            controller: 'Setup'
            action: 'index'
Famelo:
  Scaff:
    modules:
      persons:
        label: 'Persons'
        arguments:
          @package: 'Beech.Party'
          @controller: 'Management\Person'
          @action: 'list'
      companies:
        label: 'Companies'
        arguments:
          @package: 'Beech.Party'
          @controller: 'Management\Company'
          @action: 'list'
