Beech:
  Ehrm:
    menu:
      administration:
        groups:
          persons:
            priority: 10
            label: 'Persons'
          companies:
            priority: 20
            label: 'Companies'
      account:
        menu:
          settings:
            label: 'Settings'
            priority: 20
            controller: 'Setup'
            action: 'index'
Famelo:
  Scaff:
    modules:
      persons:
        label: 'Persons'
        arguments:
          @package: 'Beech.Party'
          @controller: 'Management\Person'
          @action: 'list'
      companies:
        label: 'Companies'
        arguments:
          @package: 'Beech.Party'
          @controller: 'Management\Company'
          @action: 'list'
      groupTypes:
        label: 'Group types'
        arguments:
          @package: 'Beech.Party'
          @controller: 'Management\Group\Type'
          @action: 'list'
