Beech:
  Ehrm:
    menu:
      administration:
        groups:
          persons:
            priority: 10
            label: 'Persons'
          companies:
            priority: 20
            label: 'Companies'

Radmiraal:
  Emberjs:
    restInterfaces:
      person:
        routePath: 'beech_party_domain_model_persons'
        model: 'Beech\Party\Domain\Model\Person'
        repository: 'Beech\Party\Domain\Repository\PersonRepository'
      company:
        routePath: 'beech_party_domain_model_companies'
        model: 'Beech\Party\Domain\Model\Company'
        repository: 'Beech\Party\Domain\Repository\CompanyRepository'