Beech:
  Document:
    allowedMimeTypes:
      - 'image/jpg'
      - 'image/jpeg'
      - 'image/gif'
      - 'image/png'
      - 'application/pdf'
      - 'text/plain'
      - 'application/msword'
      - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      - 'application/vnd.openxmlformats-officedocument.wordprocessingml.template'
      - 'application/vnd.ms-excel'
      - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
