Beech:
  Ehrm:
    modules:
      admin:
        menu:
          documentList:
            label: 'Documents'
            priority: 20
            menuGroup: 'main:manage'
            package: 'Beech.Document'
            controller: 'Management\Document'
            resource: 'ManagementControllers'
            action: 'index'
Document:
  allowedFileExtensions: 'jpg, jpeg, gif, png, pdf'