-
  name: 'Login'
  uriPattern: 'login.html'
  defaults:
    '@package': 'Beech.Ehrm'
    '@controller': 'Login'
    '@action': 'login'
    '@format': 'html'

-
  name: 'Default'
  uriPattern: ''
  defaults:
    '@package': 'Beech.Ehrm'
    '@controller': 'Standard'
    '@action': 'index'
    '@format': 'html'