-
  name: 'Login'
  uriPattern: 'login.html'
  defaults:
    '@package': 'Beech.Ehrm'
    '@controller': 'Login'
    '@action': 'login'
    '@format': 'html'

-
  name: 'Wizard'
  uriPattern: 'wizard/show/{formPersistenceIdentifier}'
  toLowerCase: false
  defaults:
    '@package': 'Beech.Ehrm'
    '@controller': 'Wizard'
    '@action': 'show'
    presetName: 'wizard'

-
  name: 'Wizard'
  uriPattern: 'wizard/{entity}/{id}'
  toLowerCase: false
  defaults:
    '@package': 'Beech.Ehrm'
    '@controller': 'Wizard'
    '@action': 'index'
    presetName: 'wizard'

-
  name: 'Default'
  uriPattern: ''
  defaults:
    '@package': 'Beech.Ehrm'
    '@controller': 'Standard'
    '@action': 'index'
    '@format': 'html'