Beech:
  Ehrm:
    menu:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
        arguments: []
      main:
        groups:
          employee:
            priority: 10
            label: 'Employees'
          organization:
            priority: 20
            label: 'Organization'
          report:
            priority: 30
            label: 'Report'
        menu:
      action:
        groups:
        menu:
      account:
        groups:
        menu:
          settings:
            label: 'Settings'
            priority: 20
            controller: 'Setup'
            action: 'index'
            transition: 'showSettings'
          management:
            label: 'Administration'
            priority: 100
            package: 'Beech.Ehrm'
            controller: 'Management\Administration'
            resource: 'ManagementControllers'
            action: 'index'
            transition: 'showAdministration'
          logout:
            label: 'Logout'
            priority: 9999
            controller: 'Login'
            action: 'logout'
    search:
      enabled: FALSE
    modules:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
    languages: [EN_en, NL_nl, PL_pl]

    resources:
      themes: []

      styleSheets:
        - 'Beech.Ehrm/StyleSheets/main.css'
        - 'Beech.Ehrm/Library/dataTables/media/css/jquery.dataTables.TwitterBootstrap.css'
        - 'Beech.Ehrm/Library/dataTables/media/css/jquery.dataTables.css'

    viewHelpers:
      partialRootPath: 'resource://Beech.Ehrm/Private/Templates/ViewHelpers/Partials/'
      templates:
        'Beech\Ehrm\ViewHelpers\Navigation\MenuViewHelper': 'resource://Beech.Ehrm/Private/Templates/ViewHelpers/Navigation/Menu.html'


TYPO3:
  Form:
    presets:
      wizard:
        title: 'Wizard'
        parentPreset: 'default'
        finisherPresets:
          'Beech.Ehrm:Database':
             implementationClassName: 'Beech\Ehrm\Finishers\DatabaseFinisher'
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://Beech.Ehrm/Private/Templates/FormElements/{@type}.html'
              partialPathPattern: 'resource://Beech.Ehrm/Private/Templates/FormElements/Partials/{@type}.html'
              layoutPathPattern: 'resource://Beech.Ehrm/Private/Templates/FormElements/Layouts/{@type}.html'
          'TYPO3.Form:Form':
            formBuilder:
              editors:
                finishers:
                  availableFinishers:
                    'Beech.Ehrm:Database':
                      label: 'Database Persistence Finisher'
                      templateName: 'Finisher-DatabaseFinisher'
  FormBuilder:
    handlebarsTemplates:
      # include the handlebars template
      Finisher-DatabaseFinisher: resource://Beech.Ehrm/Private/Templates/FormBuilder/DatabaseFinisher.html

Radmiraal:
  Emberjs:
    handlebar:
      view:
        assignHelpers:
          mainmenu:
            mainMenuItems:
              class: 'Beech\Ehrm\Helper\SettingsHelper'
              method: 'getMenuItems'
              arguments: ['main']
            actionMenuItems:
              class: 'Beech\Ehrm\Helper\SettingsHelper'
              method: 'getMenuItems'
              arguments: ['action']
            accountMenuItems:
              class: 'Beech\Ehrm\Helper\SettingsHelper'
              method: 'getMenuItems'
              arguments: ['account']
    applications:
      MisterMaks:
        mvc:
          controller:
            application: []
            dashboard: []
            administration: []
            management: []
            settings: []
            moduleTask:
              templateName: 'module-fullwidth'
            allTodos:
              templateName: 'alltodos'
            document:
              templateName: 'module-fullwidth'
            dashboardWidget:
              templateName: 'dashboardwidget'


        router:
          defaults:
            outlets: []
          dashboard:
            path: '/'
            outlets:
              view:
                target: 'applicationController'
                controller: 'dashboard'
                context: 'App.Todo.find()'
          moduleDocument:
            path: '/documents'
            outlets:
              view:
                target: 'applicationController'
                controller: 'moduleDocument'
          moduleTask:
            path: '/tasks'
            outlets:
              view:
                target: 'applicationController'
                controller: 'moduleTask'
          management:
            path: '/management'
            outlets:
              view:
                target: 'applicationController'
                controller: 'management'
          administration:
            path: '/administration'
            outlets:
              view:
                target: 'applicationController'
                controller: 'administration'
          settings:
            path: '/settings'
            outlets:
              view:
                target: 'applicationController'
                controller: 'settings'
