Beech:
  Ehrm:
    languages: ['en_EN', 'nl_NL', 'pl_PL']

    resources:
      themes: []

      styleSheets:
        - 'Beech.Ehrm/Library/bootstrap/css/bootstrap.css'
        - 'Beech.Ehrm/Library/bootstrap/css/bootstrap-responsive.css'
        - 'Beech.Ehrm/Library/fontawesome/css/font-awesome.min.css'
        - 'Beech.Ehrm/Library/dataTables/media/css/jquery.dataTables.TwitterBootstrap.css'
        - 'Beech.Ehrm/Library/dataTables/media/css/jquery.dataTables.css'
        - 'Beech.Ehrm/Library/bootstrap-notify/css/bootstrap-notify.css'
        - 'Beech.Ehrm/Library/bootstrap-notify/css/styles/alert-blackgloss.css'
        - 'Beech.Ehrm/Library/bootstrap-notify/css/styles/alert-notification-animations.css'
        - 'Beech.Ehrm/Library/datepicker/css/datepicker.css'

      javaScript:
        libraries:
          - 'Beech.Ehrm/Library/bootstrap/js/bootstrap.min.js'
          - 'Beech.Ehrm/Library/bootstrap-notify/js/bootstrap-notify.js'
          - 'Beech.Ehrm/Library/jquery.gracefulWebSocket.js'
          - 'Beech.Ehrm/Library/jquery.form.js'
          - 'Beech.Ehrm/Library/jquery.cookie.js'
          - 'Beech.Ehrm/Library/datepicker/js/bootstrap-datepicker.js'

        sources:
          init: 'Beech.Ehrm/JavaScript/Init.js'
          moduleHandler: 'Beech.Ehrm/JavaScript/ModuleHandler.js'
          moduleMixin: 'Beech.Ehrm/JavaScript/Mixins/Module.js'
          ajaxModuleMixin: 'Beech.Ehrm/JavaScript/Mixins/AjaxModule.js'
          modelRouteMixin: 'Beech.Ehrm/JavaScript/Mixins/ModelRoute.js'
          application: 'Beech.Ehrm/JavaScript/Application.js'
          router: 'Beech.Ehrm/JavaScript/Router.js'
          breadcrumbMenu: 'Beech.Ehrm/JavaScript/Component/UserInterface/BreadcrumbMenu.js'
          taskModuleAllTodos: 'Beech.Ehrm/JavaScript/Component/UserInterface/TaskWidget.js'
          notificationService: 'Beech.Ehrm/JavaScript/Service/Notification.js'

    viewHelpers:
      partialRootPath: 'resource://Beech.Ehrm/Private/Templates/ViewHelpers/Partials/'
      templates:
        'Beech\Ehrm\ViewHelpers\Navigation\MenuViewHelper': 'resource://Beech.Ehrm/Private/Templates/ViewHelpers/Navigation/Menu.html'

TYPO3:
  Form:
    presets:
      wizard:
        title: 'Wizard'
        parentPreset: 'default'
        finisherPresets:
          'Beech.Ehrm:Database':
             implementationClassName: 'Beech\Ehrm\Finishers\DatabaseFinisher'
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://Beech.Ehrm/Private/Templates/FormElements/{@type}.html'
              partialPathPattern: 'resource://Beech.Ehrm/Private/Templates/FormElements/Partials/{@type}.html'
              layoutPathPattern: 'resource://Beech.Ehrm/Private/Templates/FormElements/Layouts/{@type}.html'
          'TYPO3.Form:Form':
            formBuilder:
              editors:
                finishers:
                  availableFinishers:
                    'Beech.Ehrm:Database':
                      label: 'Database Persistence Finisher'
                      templateName: 'Finisher-DatabaseFinisher'
  FormBuilder:
    handlebarsTemplates:
      # include the handlebars template
      Finisher-DatabaseFinisher: resource://Beech.Ehrm/Private/Templates/FormBuilder/DatabaseFinisher.html

  Flow:
    session:
      cookie:

        # Also allow JavaScript to retrieve the session cookie so we can pass
        # it to the WebSocket service
        httponly: FALSE
