Beech:
  Ehrm:
    menu:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
      main:
        groups:
          manage:
            priority: 40
            label: 'Beheer'
          new:
            priority: 10
            label: 'Nieuw'
          edit:
            priority: 20
            label: 'Bewerk'
          report:
            priority: 30
            label: 'Rapporteer'
        menu:
      action:
        groups:
        menu:
      account:
        groups:
        menu:
          settings:
            label: 'Instellingen'
            priority: 20
            package: 'Beech.Party'
            controller: 'Management\Company'
            action: 'list'
          log:
            label: 'Logboek'
            priority: 30
            package: 'Beech.Ehrm'
            controller: 'Login'
            action: 'logout'
          logout:
            label: 'Uitloggen'
            priority: 99
            package: 'Beech.Ehrm'
            controller: 'Login'
            action: 'logout'
    modules:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
