Beech:
  Ehrm:
    menu:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
      main:
        groups:
          manage:
            priority: 40
            label: 'Manage'
          new:
            priority: 10
            label: 'New'
          edit:
            priority: 20
            label: 'Edit'
          report:
            priority: 30
            label: 'Report'
        menu:
      action:
        groups:
        menu:
      account:
        groups:
        menu:
          logout:
            label: 'Logout'
            priority: 99
            controller: 'Login'
            action: 'logout'
    modules:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
TYPO3:
  Form:
    presets:
      wizard:
        title: 'Wizard'
        parentPreset: 'default'
        finisherPresets:
          'Beech.Ehrm:Database':
             implementationClassName: 'Beech\Ehrm\Finishers\DatabaseFinisher'
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://Beech.Ehrm/Private/Form/{@type}.html'
              partialPathPattern: 'resource://Beech.Ehrm/Private/Form/Partials/{@type}.html'
              layoutPathPattern: 'resource://Beech.Ehrm/Private/Form/Layouts/{@type}.html'
          'TYPO3.Form:Form':
            formBuilder:
              editors:
                finishers:
                  availableFinishers:
                    'Beech.Ehrm:Database':
                      label: 'Database Persistence Finisher'
                      templateName: 'Finisher-DatabaseFinisher'
  FormBuilder:
    handlebarsTemplates:
      # include the handlebars template
      Finisher-DatabaseFinisher: resource://Beech.Ehrm/Private/FormBuilderTemplates/DatabaseFinisher.html
LanguageSetter:
  user:
    john: en
    bram: nl
    karol: pl
