Beech:
  Ehrm:
    menu:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
      main:
        groups:
          employee:
            priority: 10
            label: 'Employees'
          organization:
            priority: 20
            label: 'Organization'
          report:
            priority: 30
            label: 'Report'
        menu:
      action:
        groups:
        menu:
      account:
        groups:
        menu:
          management:
            label: 'Administration'
            priority: 100
            package: 'Beech.Ehrm'
            controller: 'Management\Administration'
            resource: 'ManagementControllers'
            action: 'index'
          setupApplication:
            label: 'Setup application'
            priority: 998
            package: 'Beech.Ehrm'
            controller: 'Setup\Application'
            resource: 'ManagementControllers'
            action: 'index'
          logmanager:
            label: 'System log'
            priority: 999
            controller: 'Log'
            resource: 'ManagementControllers'
          logout:
            label: 'Logout'
            priority: 9999
            controller: 'Login'
            action: 'logout'
    search:
      enabled: FALSE
    modules:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
    languages: [EN_en, NL_nl, PL_pl]

TYPO3:
  Form:
    presets:
      wizard:
        title: 'Wizard'
        parentPreset: 'default'
        finisherPresets:
          'Beech.Ehrm:Database':
             implementationClassName: 'Beech\Ehrm\Finishers\DatabaseFinisher'
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://Beech.Ehrm/Private/Form/{@type}.html'
              partialPathPattern: 'resource://Beech.Ehrm/Private/Form/Partials/{@type}.html'
              layoutPathPattern: 'resource://Beech.Ehrm/Private/Form/Layouts/{@type}.html'
          'TYPO3.Form:Form':
            formBuilder:
              editors:
                finishers:
                  availableFinishers:
                    'Beech.Ehrm:Database':
                      label: 'Database Persistence Finisher'
                      templateName: 'Finisher-DatabaseFinisher'
  FormBuilder:
    handlebarsTemplates:
      # include the handlebars template
      Finisher-DatabaseFinisher: resource://Beech.Ehrm/Private/FormBuilderTemplates/DatabaseFinisher.html

  Flow:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          LdapProvider:
            provider: TYPO3\LDAP\Security\Authentication\Provider\LDAPProvider
            providerOptions:
              type: 'LDAP'
              host: '172.31.100.1'
              port: 389
              baseDn: 'dc=beech,dc=it'

              bind:
                anonymous: TRUE

              ldapOptions:
                protocol_version: 3

              filter:
                account: '(uid=?)'
                ignoreDomain: TRUE

            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'login.html'

          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'login.html'

Famelo:
  Scaff:
    modules:
      logViewer:
        label: 'Log Viewer'
        arguments:
          @package: 'Beech.Ehrm'
          @controller: 'Log'
          @action: 'index'
      setup:
        label: 'Setup'
        arguments:
          @package: 'Beech.Ehrm'
          @controller: 'Setup'
          @action: 'index'
