Beech:
  Ehrm:
    menu:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
      main:
        groups:
          manage:
            priority: 40
            label: 'Beheer'
          new:
            priority: 10
            label: 'Nieuw'
          edit:
            priority: 20
            label: 'Bewerk'
          report:
            priority: 30
            label: 'Rapporteer'
        menu:
          test:
            label: 'Something'
            priority: 10
      action:
        menu:
          admin:
            label: 'Admin'
            priority: 10
            resource: 'Ehrm_Admin_Controller'
          logout:
            label: 'Uitloggen'
            priority: 99
            controller: 'Login'
            action: 'logout'
    modules:
      defaults:
        package: 'Beech.Ehrm'
        controller: 'Standard'
        action: 'index'
      admin:
        config:
          label: 'Admin'
        menu:
          index:
            label: 'Admin index'
            priority: 10
            menuGroup: 'main:manage'
            resource: 'Ehrm_Controller'
      timecard:
        config:
          label: 'Tijdregistratie'
        menu:
          index:
            label: 'Admin index'
            priority: 20
            menuGroup: 'main:manage'
      absence:
        config:
          label: 'Verlof & verzuim'
        menu:
          new:
            label: 'Test'
            priority: 40
            menuGroup: 'main:new'

