##
# Subroutes for Party package
#
-
  name: 'Beech Party'
  uriPattern: '<PartySubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    PartySubroutes:
      package: 'Beech.Party'

##
# EHRM.Common subroutes
#

-
  name: 'Beech EHRM'
  uriPattern: '<EHRMSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    EHRMSubroutes:
      package: 'Beech.Ehrm'

##
# Flow subroutes
#

-
  name: 'Flow'
  uriPattern: '<FlowSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    FlowSubroutes:
      package: 'TYPO3.Flow'