-
  name: 'Temp route for Tasks REST controller'
  uriPattern: 'rest/tasks'
  defaults:
    '@format': 'json'
    '@package': 'Beech.Task'
    '@controller': 'Rest\Task'
    '@action': 'list'

##
# TYPO3.UserManagement
#

-
  name: 'TYPO3 UserManagement'
  uriPattern: '<TYPO3UserManagementSubroutes>'
  subRoutes:
    TYPO3UserManagementSubroutes:
      package: 'TYPO3.UserManagement'

##
# EHRM.Common subroutes
#
-
  name: 'Beech EHRM'
  uriPattern: '<BeechEhrmSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    BeechEhrmSubroutes:
      package: 'Beech.Ehrm'

##
# Radmiraal.Emberjs subroutes
#
-
  name: 'Emberjs'
  uriPattern: '<RadmiraalEmberjsSubroutes>'
  defaults:
    '@format': 'js'
  subRoutes:
    RadmiraalEmberjsSubroutes:
      package: 'Radmiraal.Emberjs'


##
# Flow subroutes
#
-
  name: 'Flow'
  uriPattern: '<FlowSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    FlowSubroutes:
      package: 'TYPO3.Flow'