##
# EHRM.Common subroutes
#

-
  name: 'Beech EHRM Common'
  uriPattern: '<EHRMCommonSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    EHRMCommonSubroutes:
      package: Beech.Ehrm.Common

##
# FLOW3 subroutes
#

-
  name: 'FLOW3'
  uriPattern: '<FLOW3Subroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    FLOW3Subroutes:
      package: TYPO3.FLOW3