##
# Subroutes for Party package
#
-
  name: 'Beech Party'
  uriPattern: '<BeechPartySubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    BeechPartySubroutes:
      package: 'Beech.Party'

##
# EHRM.Common subroutes
#

-
  name: 'Beech EHRM'
  uriPattern: '<BeechEhrmSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    BeechEhrmSubroutes:
      package: 'Beech.Ehrm'

##
# EHRM.Document subroutes
#

-
  name: 'Beech Document'
  uriPattern: '<BeechDocumentSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    BeechDocumentSubroutes:
      package: 'Beech.Document'

##
# Flow subroutes
#
-
  name: 'Flow'
  uriPattern: '<FlowSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    FlowSubroutes:
      package: 'TYPO3.Flow'
