##
# EHRM.Common subroutes
#
-
  name: 'Beech EHRM'
  uriPattern: '<BeechEhrmSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    BeechEhrmSubroutes:
      package: 'Beech.Ehrm'

##
# EHRM.Task subroutes
#
-
  name: 'Beech Task'
  uriPattern: '<BeechTaskSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    BeechTaskSubroutes:
      package: 'Beech.Task'

##
# Radmiraal.Emberjs subroutes
#
-
  name: 'Emberjs'
  uriPattern: '<RadmiraalEmberjsSubroutes>'
  defaults:
    '@format': 'js'
  subRoutes:
    RadmiraalEmberjsSubroutes:
      package: 'Radmiraal.Emberjs'


##
# Flow subroutes
#
-
  name: 'Flow'
  uriPattern: '<FlowSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    FlowSubroutes:
      package: 'TYPO3.Flow'