##
# EHRM.Common subroutes
#

-
  name: 'Beech EHRM'
  uriPattern: '<EHRMSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    EHRMSubroutes:
      package: Beech.Ehrm


##
# FLOW3 subroutes
#

-
  name: 'FLOW3'
  uriPattern: '<FLOW3Subroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    FLOW3Subroutes:
      package: TYPO3.FLOW3