TYPO3:
  FLOW3:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          LdapProvider:
            provider: TYPO3\LDAP\Security\Authentication\Provider\LDAPProvider
            providerOptions:
              type: 'LDAP'
              host: '172.31.100.1'
              port: 389
              baseDn: 'dc=beech,dc=it'

              bind:
                anonymous: TRUE

              ldapOptions:
                protocol_version: 3

              filter:
                account: '(uid=?)'
                ignoreDomain: TRUE

            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'login.html'

          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'login.html'

  DocTools:
    bundles:
      Ehrm:
        documentationRootPath: %FLOW3_PATH_ROOT%Documentation/
        configurationRootPath: %FLOW3_PATH_PACKAGES%Tools/TYPO3.DocTools/Resources/Private/Themes/FLOW3/
        renderedDocumentationRootPath: %FLOW3_PATH_DATA%Documentation/Beech.Ehrm/
        renderingOutputFormat: 'html'
